[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "python311", 
  "python311Packages.pip", 
  "python311Packages.virtualenv",
  "gcc",
  "gnumake",
  "python311Packages.setuptools"
]

[phases.install]
cmds = [
  "ln -sf /bin/bash /bin/sh",
  "npm ci",
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r python-requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PATH = "/opt/venv/bin:$PATH"