[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.pip",
  "bash",
  "coreutils"
]

# Disable Caddy phase - we use Express to serve the app
[phases.caddy]
cmds = []

[phases.install]
cmds = [
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "python3 -m venv --copies /app/.venv",
  "/app/.venv/bin/pip install --no-cache-dir --upgrade pip",
  "/app/.venv/bin/pip install --no-cache-dir -r python-requirements.txt",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
PYTHON_KEYRING_BACKEND = "keyring.backends.null.Keyring"
PYTHONUNBUFFERED = "1"
PATH = "/app/.venv/bin:$PATH"
