[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "python311", 
  "python311Packages.pip", 
  "python311Packages.virtualenv",
  "gcc",
  "gnumake",
  "python311Packages.setuptools",
  "coreutils"
]

[phases.install]
cmds = [
  "npm ci --build-from-source",
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r python-requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PATH = "/opt/venv/bin:$PATH"
PYTHON_KEYRING_BACKEND = "keyring.backends.null.Keyring"