[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "python311", 
  "python311Packages.pip", 
  "python311Packages.virtualenv",
  "bash",
  "coreutils"
]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install --upgrade pip && pip install -r python-requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PYTHON_KEYRING_BACKEND = "keyring.backends.null.Keyring"