[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "pip install --user -r python-requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"